### ISSUE TITLE
closing the tab does not seem to issue a kill signal

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [paradoxxxzero/butterfly#100]
I am running a node script with butterfly, and I have the following code: 

```
process.on('exit', exitHandler.bind(null, {cleanup:true, exit: true}));

//catches ctrl+c event
process.on('SIGINT', exitHandler.bind(null, {cleanup: true, exit:true}));

//catches uncaught exceptions
process.on('uncaughtException', exitHandler.bind(null, {cleanup: true, exit:true}));
```

none of these seem to fire when I am closing the tab in the browser. 

am I doing something wrong?

**Comment by paradoxxxzero** [comment]
Can you try now with the git version?

**Comment by guy-mograbi-at-gigaspaces** [comment]
actually, it seems the problem is in log4js.. the file appender does not flush properly. so I didn't see the logs.. 

https://github.com/nomiddlename/log4js-node/issues/148

it works fine.
