### ISSUE TITLE
How to auto login when open a butterfly web page?

### ISSUE THREAD

**Issue by Gwill** [paradoxxxzero/butterfly#101]
How to auto login when open a butterfly web page?

**Comment by Benoit-Besnier** [comment]
You have two way to do this : 
  - Launch butterfly server with -login=false  --unsecure (can also be change in .conf file). Then your link should be something like http://YOUR_IP:57575/user/NAMEUSER
  - If you don't want to disable the login for some reasons, you can do it with a link like this : http://YOUR_IP:57575/user/NAMEUSER#PASSWD (i didn't try this one but should work)

Read this issues [https://github.com/paradoxxxzero/butterfly/issues/16](url) should help you.

**Comment by paradoxxxzero** [comment]
Just use a certificate :+1: http://paradoxxxzero.github.io/2014/03/21/butterfly-with-ssl-auth.html

**Comment by Gwill** [comment]
THX!
