### ISSUE TITLE
ImportError: No module named tcpserver

### ISSUE THREAD

**Issue by frank0718** [paradoxxxzero/butterfly#103]
pip install butterfly

Successfully installed backports-abc-0.4 butterfly-2.0.2 singledispatch-3.4.0.3 tornado-4.3 tornado-systemd-1.0.1

then start :

butterfly

Traceback (most recent call last):
  File "/usr/local/bin/butterfly.server.py", line 23, in <module>
    import tornado_systemd
  File "/usr/local/lib/python2.7/dist-packages/tornado_systemd/__init__.py", line 3, in <module>
    from tornado.tcpserver import TCPServer
ImportError: No module named tcpserver

python 
Python 2.7.3 (default, Feb 27 2014, 20:00:17) 

any useful suggestion ?

**Comment by paradoxxxzero** [comment]
Your install of Tornado seems broken

**Comment by frank0718** [comment]
my problem !     two tornado version in my python pacakage path ; fixed
