### ISSUE TITLE
basepath option for routes

### ISSUE THREAD

**Issue by bryfry** [paradoxxxzero/butterfly#104]
Would it be possible to add a configuration option for a BasePath at which butterfly runs?

For example `butterfly.server.py --basepath="butterfly"` would set all of the /ws/, /static/, etc routes to be accessible at example.com/butterfly/[route]/

This would enable much simpler reverse proxy configurations!

The default would be empty and wouldn't affect any other deployment scenarios.
#7 is a perfect example of lots of people trying to work around the fact that all of these paths are 'hard coded' to run at the root path.

Thanks for any input!

**Comment by paradoxxxzero** [comment]
I added the uri_root_path option, can you try with:
```bash
butterfly.server.py --uri-root-path="butterfly"
```
