### ISSUE TITLE
Embedding butterfly

### ISSUE THREAD

**Issue by buzypi** [paradoxxxzero/butterfly#107]
I noticed that the butterfly terminal uses a lot of global event listeners and so looks like it's meant to be used stand-alone. I was wondering it is possible to cleanly embed butterfly terminal in an existing web application?

**Comment by paradoxxxzero** [comment]
butterfly is an application and is not meant to be embedded. Please have a look at [xterm.js](https://github.com/sourcelair/xterm.js)
