### ISSUE TITLE
Implement cursor blinking in CSS

### ISSUE THREAD

**Issue by vktec** [paradoxxxzero/butterfly#123]
CSS is perfectly capable of blinking the cursor, and doing it in CSS would provide easier customisation, as themes could simply override that CSS rule to change or disable blinking.

Below is an HTML page which runs in browsers using the `-webkit` vendor prefix. It could be easily adapted to support Firefox, etc. as well.

```html
<style>
  body {
    background: black;
    font-family: monospace;
  }
  .blink {
    color: black;
    -webkit-animation: 1s step-start 0s infinite normal blink_cursor;
  }
  @-webkit-keyframes blink_cursor {
    0% { color: #fff; }
    50% { color: #000; }
    100% { color: #fff; }
  }
</style>
<span class="blink">&#x2588;</span>
```

In under 15 lines of CSS (not counting extra vendor prefixes) we can accomplish what takes almost twice that many lines of Javascript to do, and in a much more flexible way. I also think that Javascript should only be used for logic if possible, and this is a step towards that.

In the actual implementation, the vendor prefix boilerplate could be mostly eliminated thanks to Sass mixins, making this quite simple to update and maintain.

I'd be happy to create a pull request for this, if you feel it would be helpful.

**Comment by paradoxxxzero** [comment]
If you want yes but pay attention that the animation should restart on every `showCursor` https://github.com/paradoxxxzero/butterfly/blob/master/coffees/term.coffee#L583

**Comment by vktec** [comment]
Ah, yes. I forgot about that. What would be the best way to disable cursor blinking in a theme?

**Comment by paradoxxxzero** [comment]
Overriding .cursor.reverse-video with .cursor

**Comment by vktec** [comment]
Prefect, thanks!

**Comment by vktec** [comment]
By the way, I think you may have meant the other way around. I did this in my theme:

```sass
.cursor
  @extend .reverse-video
```

**Comment by paradoxxxzero** [comment]
Yes that's it

Le mar. 6 déc. 2016 à 21:38, Samadi van Koten <notifications@github.com> a
écrit :
