### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by lukasp2** [paradoxxxzero/butterfly#124]
Hi,

i followed this how-to: https://github.com/paradoxxxzero/butterfly/wiki/Butterfly-with-nginx-reverse-proxy-and-https

When I open my https URL I see only a black web-page.

What could be wrong?

Thank you,
Lukas

**Comment by paradoxxxzero** [comment]
Do you have some logs in the js console?

**Comment by lukasp2** [comment]
Which logs do you need? Can you tell me the location ? Sorry but I'm not a pro :-)

**Comment by paradoxxxzero** [comment]
Depends on your browser i.e.  https://developer.chrome.com/devtools

**Comment by lukasp2** [comment]
Firefox can not connect to the server under wss://XXXX.ddns.net:4435/butterfly/ws/ aufbauen. main.min.js:3:593

WebSocket error Arguments { , 3 weitere… } main.min.js:3:848
WebSocket closed Arguments { , 3 weitere… } main.min.js:3:1347
TypeError: l is null

**Comment by paradoxxxzero** [comment]
You have to define a route for the websockets too in nginx. See
https://www.nginx.com/blog/websocket-nginx/

**Comment by lukasp2** [comment]
Thank you, I will check it and give you response

**Comment by lukasp2** [comment]
Hmm, I'm not able to get it running :-(

**Comment by paradoxxxzero** [comment]
Did you take a look at #7

**Comment by lukasp2** [comment]
Yes, same problem. I don't know what I'm doing wrong. I followed this how-to step by step: https://github.com/paradoxxxzero/butterfly/wiki/Butterfly-with-nginx-reverse-proxy-and-https

**Comment by lukasp2** [comment]
Hi,

it's running now!

Other question: My nginx is running on SSL via Let's Encrypt certificate. Possible to run Butterfly via ssl ? Currently butterfly runs only via normal HTTP.

Thank you,
Lukas

**Comment by paradoxxxzero** [comment]
What did you do to make it work?
Butterfly runs with ssl by default but if you use a reverse proxy, you have
to enable it on nginx side.

**Comment by lukasp2** [comment]
any idea?

**Comment by paradoxxxzero** [comment]
For this
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
 ?

**Comment by lukasp2** [comment]
My Problem is not the Let's Encrypt SSL Certificate for my Webserver. I can access butterfly via HTTP but not via HTTPS.

Have the same problem -> https://github.com/paradoxxxzero/butterfly/issues/124#issuecomment-268192387

**Comment by paradoxxxzero** [comment]
Do you have any log server side ? (With DEBUG=True)

**Comment by lukasp2** [comment]
do you mean nginx log ? or butterfly log?

**Comment by paradoxxxzero** [comment]
Butterfly, if the socket crash it must be some traces.

**Comment by lukasp2** [comment]
The Problem is:

> Firefox can not establish connection to the server under wss://XXXX.ddns.net:4435/butterfly/ws/ .
> main.min.js:3:593
> 
> WebSocket error Arguments { , 3 weitere… } main.min.js:3:848
> WebSocket closed Arguments { , 3 weitere… } main.min.js:3:1347
> TypeError: l is null

When I'm opening butterfly via HTTP, everything is ok...

**Comment by paradoxxxzero** [comment]
It depends on how you run butterfly, if it's with systemd you should have logs in journalctl, otherwise it's on stdout.
If the websocket crash there will be logs, if it can't connect at all to wss://XXXX.ddns.net:4435/butterfly/ws/ it's a network / nginx configuration issue.

**Comment by lukasp2** [comment]
Hi,

i changed the SSL Port from 4435 to 443 and now I'm able to access butterfly via HTTPS.
How I can get butterfly running via HTTPS Port 4435 ?

**Comment by milehighrockstar** [comment]
Hi, 
I'm having an issue running nginx as a reverse proxy for butterfly when the URL ends with anything other than the root "/", for example:

- http://rev-proxy:8755 works correctly
- http://rev-proxy:8755/butterfly fails.

I have the same error when butterfly is installed 2 different linux distros ( Debian and Alpine):

- Nginx 1.10.2 (w/substitution module) on Debian 8.6 and butterfly on same host.
- Nginx 1.10.2 (w/substitution module) on Debian 8.6 on the host, and butterfly running in an Alpine Linux LXC environment.  

My nginx configuration:

server {
  listen 8755;
  location /butterfly {
    rewrite ^/butterfly/?(.*) /$1 break;
    proxy_pass http://127.0.0.1:57575;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_connect_timeout 7d;
    proxy_send_timeout 7d;       
    proxy_read_timeout 7d; 
    subs_filter_types text/html text/css text/xml application/javascript;
    subs_filter /style.css '/butterfly/style.css';
    subs_filter /static '/butterfly/static';
    subs_filter /ws '/butterfly/ws';
    subs_filter location.pathname '"/"';
  }

Confirmed to be working correctly:

- Nginx correctly proxies ports & locations when for http/s (non-socket).
- Nginx correctly performs substitution.
- Butterfly works correctly when the URL is at root, "/", e.g., http://rev-proxy:8755/

So for the URL of "http://rev-proxy:8755/butterfly" , the debug output from the butterfly-tornado server is the following:

butterfly.server.py --host=127.0.0.1 --unsecure

[I 170103 17:05:55 butterfly.server:297] Starting server
[I 170103 17:05:55 butterfly.server:306] Starting loop
[W 170103 17:05:55 butterfly.server:317] Butterfly is ready, open your browser to: http://127.0.0.1:57575/
[I 170103 17:06:05 web:2028] 200 GET / (127.0.0.1) 2.40ms
[I 170103 17:06:05 web:2028] 200 GET /static/main.css?v=e90321e6c69148611e57fc1fcdab28a9 (127.0.0.1) 4.42ms
[I 170103 17:06:05 web:2028] 200 GET /static/html-sanitizer.js?v=c54621161aedf5faa8aeb98dd347acf1 (127.0.0.1) 1.08ms
[I 170103 17:06:05 web:2028] 200 GET /static/main.min.js?v=2211336da9f64cbc4baa395eb18bda0a (127.0.0.1) 1.35ms
[I 170103 17:06:05 web:2028] 200 GET /static/ext.min.js?v=e3fb5465e1eae3f0db2d180a9e887393 (127.0.0.1) 1.20ms
[E 170103 17:06:06 web:1553] Uncaught exception GET /ws/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='rev-proxy', method='GET', uri='/ws/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://rev-proxy:8755', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Sec-Websocket-Version': '13', 'Connection': 'upgrade', 'Sec-Websocket-Key': 'W4BeFcSAWB+2/16HWlLtqw==', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36', 'Dnt': '1', 'Host': 'rev-proxy', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 1430, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 1632, in wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/websocket.py", line 175, in get
        self.finish(log_msg)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/websocket.py", line 400, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 931, in finish
        self.write(chunk)
      File "/usr/local/lib/python2.7/dist-packages/butterfly/routes.py", line 254, in write
        if self.session and self.secure_user:
    AttributeError: 'TermWebSocket' object has no attribute 'session'
[E 170103 17:06:06 web:1001] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 999, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 1021, in write_error
        self.write(line)
      File "/usr/local/lib/python2.7/dist-packages/butterfly/routes.py", line 254, in write
        if self.session and self.secure_user:
    AttributeError: 'TermWebSocket' object has no attribute 'session'
[E 170103 17:06:06 web:2028] 500 GET /ws/ (127.0.0.1) 1.56ms
[W 170103 17:06:06 web:2028] 404 GET /static/main.min.js.map (127.0.0.1) 0.60ms
[W 170103 17:06:06 web:2028] 404 GET /static/ext.min.js.map (127.0.0.1) 0.66ms
[I 170103 17:06:06 web:2028] 200 GET /static/images/favicon.png?v=02b0894b1d5c47b396f56cd32e80618d (127.0.0.1) 0.65ms

Browser output in Chrome dev-tools console:

WebSocket connection to 'ws://rev-proxy:8755/butterfly/ws/' failed: Error during WebSocket handshake: Unexpected response code: 500
WrappedWebSocket @ VM162:97
WrappedWebSocket @ VM181:35
(anonymous) @ main.min.js?v=2211336…:3
main.min.js?v=2211336…:3 WebSocket error [Event]
main.min.js?v=2211336…:3 WebSocket closed [CloseEvent]
main.min.js?v=2211336…:3 Uncaught TypeError: Cannot read property 'write' of null
    at main.min.js?v=2211336…:3

The browser is displaying a black terminal screen with no text.  The html, javascript and css appear to load correctly with "butterfly" prefixed to the associated resource paths.  

The rewrite and substitution in nginx appears to be working, but the socket connection fails.  Any ideas to fix this?

**Comment by xdtianyu** [comment]
Hi, I have updated the wiki. Please try add `proxy_set_header Origin "$scheme://$host";` in your `nginx` config. 

If your are using different port other than `443`, the `websocket` will fail.

It turns out [tornado/websocket.py#L175](https://github.com/tornadoweb/tornado/blob/ac340a732875ed48663d756d0aee838de7dca6cb/tornado/websocket.py#L175) is doing something with `Origin` header. Thanks @PeterCxy correcting this issue.

**Comment by PeterCxy** [comment]
@xdtianyu It's not about tornado. See https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/routes.py#L142 , it blocks all unauthorized origins other than $scheme://$host, which is not satisfied when going through a Nginx proxy.

**Comment by jiong210** [comment]
@milehighrockstar Do you have resolved your problem? I have the same problem.Please help.

**Comment by PeterCxy** [comment]
@jiong210 see the comment by @xdtianyu , that fixes the problem.

**Comment by jiong210** [comment]
@PeterCxy thank you very much.

**Comment by midshipmanorg** [comment]
This is not working for me. I configured NGINX according to the wiki article. Version 2.0.1 of butterfly works flawlessly with it. Any version above it fails to open a prompt with the following error log

[E 170220 19:06:04 web:1548] Uncaught exception GET /ctl/session/87a340b5-1d40-4878-9f23-9330720acb99 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='my.host.org', method='GET', uri='/ctl/session/87a340b5-1d40-4878-9f23-9330720acb99', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Authorization': 'Basic bWlkc2hpcG1hbjpzcGVlZGVyWDU4IyEj', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits', 'Upgrade': 'websocket', 'Cache-Control': 'no-cache', 'Sec-Websocket-Version': '13', 'Cookie': '__cfduid=d5ec278a5b8bd3da9c0964dafc8bd07db1477681629; _ga=GA1.2.1620976147.1479128443', 'Sec-Websocket-Key': '7FthJNzVQcDEhRUypJ+z5Q==', 'Host': 'bfly.midshipman.org', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Origin': 'https://bfly.midshipman.org', 'Connection': 'upgrade', 'Pragma': 'no-cache', 'Accept-Language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,fr;q=0.2,sq;q=0.2', 'Accept-Encoding': 'gzip, deflate, sdch, br'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado-4.4.2-py3.4-linux-x86_64.egg/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado-4.4.2-py3.4-linux-x86_64.egg/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/dummy/butterfly/butterfly/terminal.py", line 325, in shell_handler
        self.send(None)  # Close all
      File "/dummy/butterfly/butterfly/terminal.py", line 111, in send
        self.broadcast(self.session, message)
      File "/dummy/butterfly/butterfly/routes.py", line 298, in broadcast
        cls.close_session(session)
      File "/dummy/butterfly/butterfly/routes.py", line 287, in close_session
        TermCtlWebSocket.sessions.get(session))
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by xdtianyu** [comment]
@midshipmanorg I'm using `butterfly v 2.0.2` which is installed via `pip install butterfly`, and it's working.

**Comment by paradoxxxzero** [comment]
@midshipmanorg do you have another error with the last commit?

**Comment by midshipmanorg** [comment]
@paradoxxxzero Strange. I don't get the error anymore but the session is still closed immediately: "ClosedThis account is currently not available"

**Comment by midshipmanorg** [comment]
@paradoxxxzero Is this even coming from butterfly? Sounds more like a general login problem...

**Comment by jwernicke** [comment]
I'm having the issue that when using `location /butterfly` in nginx config, `wss://HOSTNAME/ctl/session/SESSION_UUID` 404s. `wss://HOSTNAME/butterfly/ws/session/SESSION_UUID` resolves fine. In `https://HOSTNAME/butterfly/static/main.min.js?v=cecea52f4d1f800f57972f0f54c3bc27`, I see `new WebSocket(q + "/ws" + k)` is rewritten to `new WebSocket(q + "/butterfly/ws" + k)`. Is `new WebSocket(q + "/ctl" + k)` also supposed to be rewritten to `new WebSocket(q + "/butterfly/ctl" + k)`? I'm having trouble figuring out where `/butterfly` gets prepended, but maybe one of y'all more familiar with the project could check it out?

**Comment by 3ch01c** [comment]
I'm having the issue that when using location /butterfly in nginx config, wss://HOSTNAME/ctl/session/SESSION_UUID 404s. wss://HOSTNAME/butterfly/ws/session/SESSION_UUID resolves fine. In https://HOSTNAME/butterfly/static/main.min.js?v=cecea52f4d1f800f57972f0f54c3bc27, I see new WebSocket(q + "/ws" + k) is rewritten to new WebSocket(q + "/butterfly/ws" + k). Is new WebSocket(q + "/ctl" + k) also supposed to be rewritten to new WebSocket(q + "/butterfly/ctl" + k)? I'm having trouble figuring out where /butterfly gets prepended, but maybe one of y'all more familiar with the project could check it out?

# pip show butterfly
Name: butterfly
Version: 3.1.5
Summary: A sleek web based terminal emulator
Home-page: https://github.com/paradoxxxzero/butterfly
Author: Florian Mounier
Author-email: paradoxxx.zero@gmail.com
License: GPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: tornado, pyOpenSSL

**Comment by NBOOK** [comment]
> I'm having the issue that when using `location /butterfly` in nginx config, `wss://HOSTNAME/ctl/session/SESSION_UUID` 404s. `wss://HOSTNAME/butterfly/ws/session/SESSION_UUID` resolves fine. When comparing `https://HOSTNAME/butterfly/static/main.min.js?v=cecea52f4d1f800f57972f0f54c3bc27` to [source](https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/static/main.min.js), I see `new WebSocket(q + "/ws" + k)` is rewritten to new `WebSocket(q + "/butterfly/ws" + k)`. Is new `WebSocket(q + "/ctl" + k)` also supposed to be rewritten to new `WebSocket(q + "/butterfly/ctl" + k)`? I'm having trouble figuring out where `/butterfly` gets prepended, but maybe one of y'all more familiar with the project could check it out?
> 
> ```
> # pip show butterfly
> Name: butterfly
> Version: 3.1.5
> Summary: A sleek web based terminal emulator
> Home-page: https://github.com/paradoxxxzero/butterfly
> Author: Florian Mounier
> Author-email: paradoxxx.zero@gmail.com
> License: GPLv3
> Location: /usr/local/lib/python2.7/dist-packages
> Requires: tornado, pyOpenSSL
> ```

Hello 3ch01c, I have exactly the problem as yours. I know this question is old but I wonder if you have found a solution? The points mentioned in this thread are already addressed but it doesn't fix the problem.
