### ISSUE TITLE
Ping to KeepAlive

### ISSUE THREAD

**Issue by wernight** [paradoxxxzero/butterfly#126]
It's frequent to have Butterfly behind some kind of frontend, for example **Nginx**. Most of the time, for safety, there is a [default timeout (`proxy-read-timeout` and `proxy-send-timeout` for Nginx reverse proxy)](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#default-configuration-options) of about 60 sec (1 minute) before disconnecting if there was not I/O.

To avoid **WebSocket** to get **closed** automatically, it'd be useful if Butterfly could manually send pings every 30 seconds or so. Any kind of user input would keep the connection alive.

See also http://stackoverflow.com/questions/23238319/websockets-ping-pong-why-not-tcp-keepalive

**Comment by wernight** [comment]
I see that [tornado has a ping method](http://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler.ping). Might work.

**Comment by PeterCxy** [comment]
I implemented it in #131
