### ISSUE TITLE
Please provide non-tornado_systemd version of the http server

### ISSUE THREAD

**Issue by yurivict** [paradoxxxzero/butterfly#127]
systemd is linuxism, and doesn't work on BSDs, for example.

Please add the check for OS and in case of not Linux please use something like this:
```
http_server = tornado.httpserver.HTTPServer(
    application, ssl_options=ssl_opts)
```

**Comment by paradoxxxzero** [comment]
The systemd wrapper is just a wrapper, it doesn't do anything if butterfly is launched without systemd.
https://github.com/paradoxxxzero/tornado-systemd/blob/master/tornado_systemd/__init__.py#L17
Reopen if you have any real bug with it.

**Comment by yurivict** [comment]
It fails on non-linux systems.

**Comment by paradoxxxzero** [comment]
Which module?

**Comment by yurivict** [comment]
tornado_systemd doesn't exist.

I had to replace its use with tornado.httpserver.HTTPServer, see above.

Anything with systemd in it doesn't exist outside Linux.

**Comment by paradoxxxzero** [comment]
https://pypi.python.org/pypi/tornado_systemd/1.0.1 should be installable on freebsd and even on windows since it doesn't depends on anything.
I agree that a hard dependency over an os specific wrapper is overkill, but handling platform specific dependencies in setup.py and providing a wheel is a never ending nightmare.

**Comment by yurivict** [comment]
I made the FreeBSD port for butterfly.
tornado_systemd port can't be created for these reasons:
* It only wraps some linux-only functionality
* It doesn't have a clear meaning/function besides this
* systemd hadn't been adopted in BSDs, and I don't think it will ever be adopted
* anything having systemd in it isn't accepted, because it is ultimately defunct in BSD

So it can't be made a dependency.
In general, it's best to make such things local in the project, not a separate project. If it was an internal class, it probably wouldn't stand out at all.

**Comment by paradoxxxzero** [comment]
This https://github.com/paradoxxxzero/butterfly/commit/17f8c1d1c9340d976e8123ceeeaaf272eb0c7f7b#diff-10dcd5152502b6fa23eb5e70e3fba389R23 should fix this.
