### ISSUE TITLE
[feature request] PAM login

### ISSUE THREAD

**Issue by yurivict** [paradoxxxzero/butterfly#129]
Please implement pam login. Make the pam profile name an argument.

Users should be able, for example, to enable the 2-factor authentication through PAM. Alternatively, any other customization of the authentication process can be set up in PAM.

**Comment by PeterCxy** [comment]
Maybe for now you can edit `/etc/pam.d/su` to achive the same purpose?

**Comment by yurivict** [comment]
@PeterCxy Thanks for the workaround!

**Comment by paradoxxxzero** [comment]
I am not against a PR about this.

**Comment by PeterCxy** [comment]
I made a simple implementation in #133
