### ISSUE TITLE
Only a black screen in firefox

### ISSUE THREAD

**Issue by yurivict** [paradoxxxzero/butterfly#130]
It only shows a black screen in firefox-50.0.1
Clicking on the other browser tab and back makes terminal to work.
Problem doesn't seem to exist in chrome.
Clicking on the URL bar and then on the black screen also makes it work.

**Comment by paradoxxxzero** [comment]
What's your version of butterfly? I can't reproduce with firefox 51.

**Comment by yurivict** [comment]
2.0.1

**Comment by yurivict** [comment]
It was completely black. Now I can't reproduce it. Will observe this more.
