### ISSUE TITLE
No font mimetypes on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [paradoxxxzero/butterfly#132]
Few themes, ex. C64 and DOS, have non-monospace fonts. They don't look good in a terminal.

**Comment by paradoxxxzero** [comment]
I'm quite sure they are https://github.com/paradoxxxzero/butterfly-themes/blob/4d352b32d6857deeafa01e3601959299bda75f0c/DOS/Perfect%20DOS%20VGA%20437%20Win.woff https://github.com/paradoxxxzero/butterfly-themes/blob/4d352b32d6857deeafa01e3601959299bda75f0c/C64/font/C64_Pro_Mono-STYLE.woff

**Comment by yurivict** [comment]
They aren't displayed as monospace in my browser.

**Comment by paradoxxxzero** [comment]
Are they loaded or you get a fallback font?

**Comment by yurivict** [comment]
C64 font is installed here:
/usr/local/lib/python2.7/site-packages/butterfly/themes/C64/font/C64_Pro_Mono-STYLE.woff

But browser is getting 500 Internal Server Error

log gets errors:
```
    HTTPServerRequest(protocol='http', host='localhost:57001', method='GET', uri='/theme/built-in-C64/font/C64_Pro_Mono-STYLE.woff', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:57001', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': 'localhost:57001', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:57001/theme/built-in-C64/style.css', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', Bugzilla_login=1; express_sid=s%3AldNbWwQIbuGINjVfPAzGjk3B2RRC2zJG.0Tm%2Bg2xyjhI7CNPpKPXWutFtTWqacnKKsexTUfYZFmQ; language=en; sixpack-clientId=56622f50883e2ee5ec0e70ee; lang=en-US; i_like_gogits=8e4e7533ba54acac; _csrf=ZJzqmqwKXHu3nguElMrE6U-PdZg6MTQ1NjY4MzA1NjY3OTM0MzUzMg%3D%3D; test=test; PHPSESSID=v5ar8ckoahm4a0s875vfnd7jk6; DEFAULTFORMAT=advanced; LASTORDER=bug_id; VERSION-Main=0.1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/site-packages/butterfly/routes.py", line 104, in get
        self.set_header("Content-Type", guess_type(fn)[0])
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 334, in set_header
        self._headers[name] = self._convert_header_value(value)
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 379, in _convert_header_value
        raise TypeError("Unsupported header value %r" % value)
    TypeError: Unsupported header value None
[E 170210 02:04:17 web:1971] 500 GET /theme/built-in-C64/font/C64_Pro_Mono-STYLE.woff (127.0.0.1) 1.86ms
```

**Comment by paradoxxxzero** [comment]
Seems like a problem with `mimetypes.guess_type` on your system. Any idea why?

Here I get:
```python
>>> import mimetypes
>>> mimetypes.guess_type('font.woff')
('application/font-woff', None)
```

**Comment by yurivict** [comment]
It prints
```
(None, None)
```

Python's mimetypes.py goes through optionally installed Apache and Netscape packages. If you have Apache installed, it will use /etc/apache2/mime.types On FreeBSD that path is actually wrong, this is why it fails. It looks like nobody cared before.

I guess you have Apache installed. But this is a very bad idea that python picks data bits from the unrelated optional packages. You will probably be better off hardcoding your own mime type lookup procedure for relevant types.

**Comment by paradoxxxzero** [comment]
I don't have apache no but anyway this is problematic since it's the python std ffs. I really don't want to implement a big mapping of every extensions with every mime types. Maybe the solution is adding an external dependency (like https://github.com/ahupp/python-magic) for exotic systems.

**Comment by yurivict** [comment]
Python looks for these files, none of which it installs:

```
knownfiles = [
    "/etc/mime.types",
    "/etc/httpd/mime.types",                    # Mac OS X
    "/etc/httpd/conf/mime.types",               # Apache
    "/etc/apache/mime.types",                   # Apache 1
    "/etc/apache2/mime.types",                  # Apache 2
    "/usr/local/etc/httpd/conf/mime.types",
    "/usr/local/lib/netscape/mime.types",
    "/usr/local/etc/httpd/conf/mime.types",     # Apache 1.2
    "/usr/local/etc/mime.types",                # Apache 1.3
    ]
```
My guess is that your OS just happens to have some of them installed.
It is a random behavior that we see here, not any kind of systematic approach.
Other flavors of linux or other OSes might not have these files installed.
