### ISSUE TITLE
win10 docker: some keys/features do not work

### ISSUE THREAD

**Issue by inkrement** [paradoxxxzero/butterfly#145]
I installed the docker version on Win10 and I use Google Chrome. The following things do not work:

 * paste from clipboard using Ctrl+V (Shift + Insert works) -> nothing happens
 * Insert "special" symbols (e.g., @ or [ ]).. I am using a german keyboard layout, but this should not be a problem.

**Comment by paradoxxxzero** [comment]
* Ctrl + c/v are not captured use ctrl + shift + c/v instead (like most terminal emulators.)
* There is a similar issue : https://github.com/paradoxxxzero/butterfly/issues/112 any information about that is welcomed.
