### ISSUE TITLE
Fake `closed`

### ISSUE THREAD

**Issue by F-TD5X** [paradoxxxzero/butterfly#167]
The webpage shows it is closed. But the session is still open and after remove the class "dead" from `<body>`, I can do what I want as nothing happened.

But it makes someone uncomfortable, so please add a "reconnect" button, or fix this problem?

**Comment by MrPessimist** [comment]
i have the same issue!. My butterfly home say "Closed"

[I 180607 10:23:37 routes:143] Websocket opened <butterfly.routes.TermWebSocket object at 0x7f864bd25160>
[I 180607 10:23:37 terminal:58] Terminal opening with session: None and socket <Socket L: 10.X.X.X:57575 R: 10.X.X.X:5699 User: None>
[E 180607 10:23:37 websocket:501] Uncaught exception in /ws
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "/usr/lib/python3.4/site-packages/butterfly/routes.py", line 180, in open
        self.request.headers['Host'], self.render_string, self.write)
      File "/usr/lib/python3.4/site-packages/butterfly/terminal.py", line 95, in __init__
        self.send('S' + motd)
      File "/usr/lib64/python3.4/site-packages/tornado/websocket.py", line 478, in _raise_not_supported_for_websockets
        raise RuntimeError("Method not supported for Web Sockets")
    RuntimeError: Method not supported for Web Sockets

**Comment by BrunoPrece** [comment]
I have this issue, besides, in some cases the ws websocket closes if it is widely used by user or is kept open for some time without interactions . The clt socket still alive after ws closes.

**Comment by fzumstein** [comment]
@BrunoPrece have a look if https://github.com/paradoxxxzero/butterfly/pull/172 fixes this for you.

**Comment by BrunoPrece** [comment]
Thankyou @fzumstein! This fix the problem. It's interesting because only when the internal proxy of my client is activated the socket closes, probably afected by keep-alive setted in client proxy. After acrescent #172 the problem was fixed.
