### ISSUE TITLE
Simulating key input by injection from parent frame.

### ISSUE THREAD

**Issue by GrahamDumpleton** [paradoxxxzero/butterfly#175]
I am trying to use butterfly through an iframe (all bits appear under same host/port, so no cross origin issues). I want to be able to have an action in the parent frame be able to send a text string into the butterfly terminal frame as if it was typed in by the user directly in the butterfly terminal, and thus run a command in the terminal. The purpose of this is for interactive learning environment, where users can click on commands in instructions displayed in parent frame and have them be run, without needing to re-enter them. I have tried various things to achieve this and having no luck so far.

I have tried using something like:

```
iframe.contentWindow.postMessage(value, iframe.contentWindow.origin)
```

with hope that message is picked and written by virtue of:

https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/static/main.js#L104

I have tried creating individual keypress events and dispatching that against various contexts within the frame.

```
iframe.contentDocument.body.dispatchEvent(evt)
```

with hope that is picked up by:

https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/static/main.js#L205

All those attempts silently didn't achieve anything.

I have tried calling functions direct on the Terminal object such as.

```
iframe.contentWindow.Terminal.prototype.keyPress(evt)
```

This approach would result in errors:

```
main.min.js?v=4e96594767258ca98721af20930b5a95:3 Uncaught TypeError: Cannot read property 'NaN' of undefined
    at Object.a.showCursor (main.min.js?v=4e96594767258ca98721af20930b5a95:3)
    at Object.a.keyPress (main.min.js?v=4e96594767258ca98721af20930b5a95:3)
    at send_to_terminal ((index):115)
    at handle_command_execute (01-exploring-the-cli-and-web-console.html?embedded=1:18)
    at HTMLButtonElement.onclick (01-exploring-the-cli-and-web-console.html?embedded=1:54)
```

Is there a built in function or way of doing things that can achieve this as is, or would butterfly need to be modified to expose a function that could be called for this purpose.

Note that I am newbie when it comes to Javascript so everything have tried has been based on Google searches. Am going to keep trying stuff and work with original git repo sources so can start adding debug to un-minified Javascript to see what is occurring.

Any suggestions of right way of doing this or changes I could make to support it most appreciated.

Thanks.

**Comment by paradoxxxzero** [comment]
If you want to write to the terminal, just use `iframe.contentWindow.butterfly.send('what you want to write')`
(butterfly is the instance of the Terminal class as you can see here https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/static/main.js#L49)

**Comment by GrahamDumpleton** [comment]
Ahhh, that is what I was missing. Didn't realise ``contentWindow.butterfly`` was actually the instance. Much thanks.

BTW, will have another PR coming at some point to add optionally enable support for ``xheaders`` option (http://www.tornadoweb.org/en/stable/httpserver.html). This way generated ``LOCATION`` environment will I hope include correct protocol when behind a HTTPS proxy.
