### ISSUE TITLE
Failing to source git prompt script

### ISSUE THREAD

**Issue by jsanders** [paradoxxxzero/butterfly#5]
At least I think that's the problem. The error is:

    bash: __git_ps1: command not found

which I believe comes from this line of my `.bash_profile`:

    export PS1='[\!] \w$(__git_ps1) \$ '

Earlier in my `.bash_profile`, I have:

    if [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
      . /usr/local/etc/bash_completion.d/git-prompt.sh
    fi

**Comment by jwebcat** [comment]
@amir20 same for me I just `source .bash_profile` on startup as well.
