### ISSUE TITLE
Doesn't play well with a reverse proxy

### ISSUE THREAD

**Issue by mediocregopher** [paradoxxxzero/butterfly#7]
I tried to set this up on my box behind a reverse proxy (nginx) so that I could provide some form of authentication and not have to open up another port, amongst other reasons. In my nginx config I had:

```
location /butterfly {
    rewrite ^/butterfly/?(.*) /$1 break;
    proxy_pass http://localhost:57575;
}
```

This worked fine in that it loaded the homepage, but unfortunately all the static assets were trying to be loaded from `/static/`, and I needed them to be from `/butterfly/static/`. I messed around with the source a bit, including setting `http_path` inside the static directory and rebuilding, but to no avail. If you can provide a pointer on how this might be fixed I can take a stab and submit a PR, but I'm not sure on where to start.

**Comment by meoow** [comment]
@boccato I copied your configuration, but butterfly shows the following when I connect.
> This account is currently not available
> Closed
