### ISSUE TITLE
How to support the Chinese input method?

### ISSUE THREAD

**Issue by longgeek** [paradoxxxzero/butterfly#75]
as title

**Comment by paradoxxxzero** [comment]
I have absolutely no idea of how it works sorry, I'm open to anything to support this.

**Comment by longgeek** [comment]
same https://github.com/paradoxxxzero/butterfly/issues/47

**Comment by PeterCxy** [comment]
The updated fork of xterm.js (https://github.com/sourcelair/xterm.js) supports IME correctly. Maybe we can just pull in the new version as dependency.

**Comment by paradoxxxzero** [comment]
Yeah that would be nice, in fact it would be really nice to merge back what can be useful for everyone but it seems the term.js/xterm.js has diverged a lot so it will be a tedious process.

**Comment by PeterCxy** [comment]
I know it's been years but I just completed CJK & IME support for Butterfly on #168
