### ISSUE TITLE
How to change butterfly terminal color theme?

### ISSUE THREAD

**Issue by longgeek** [paradoxxxzero/butterfly#76]
e.g. tomorrow-night

**Comment by paradoxxxzero** [comment]
Butterfly is themable in sass / css, you can create a file /etc/butterfly/style.sass or ~user/.butterfly/style.sass and copy/rewrite the original https://github.com/paradoxxxzero/butterfly/blob/master/butterfly/sass/main.sass

**Comment by paradoxxxzero** [comment]
I added some instructions in `butterfly_help` in the upcoming v2.
