### ISSUE TITLE
nginx reverse proxy - user set to 'nginx'

### ISSUE THREAD

**Issue by jinmel** [paradoxxxzero/butterfly#93]
The user is set to 'nginx' when using reverse proxy - the butterfly terminal skips the 'login:' phase and asks for password only.
Using reverse proxy is necessary when using a https connection directly from nginx settings. However there seems to be no option for making login user anonymous(i.e. do not set user for any circumstances). I think a new option for butterfly.server.py should be added since free ssl certificates are getting popular (https://letsencrypt.org/)

**Comment by paradoxxxzero** [comment]
Can you please test again with the last commit?
