### ISSUE TITLE
login=False is broken in 2.0.1. works in 2.0.0

### ISSUE THREAD

**Issue by GuyMograbi** [paradoxxxzero/butterfly#96]
Hi, 

my script took to the latest and suddenly I was prompted for login even though using login=False. 
downgrade to 2.0.0 works great. 

thanks for this awesome project.

**Comment by paradoxxxzero** [comment]
Can you post the trace of --debug --more?

**Comment by iscreen** [comment]
in terminal.py line 177 if self.callee is None even if assign unsecure or login options, it still need to input login

**Comment by paradoxxxzero** [comment]
Can you try with my last commit ? It should be ok now

**Comment by guy-mograbi-at-gigaspaces** [comment]
how do I install your last commit with pip?

**Comment by Le-Stagiaire** [comment]
Same issue here, how do we install it?

**Comment by paradoxxxzero** [comment]
```bash
  pip install git+https://github.com/paradoxxxzero/butterfly.git --upgrade
```

**Comment by guy-mograbi-at-gigaspaces** [comment]
actually, it seems that the problem is now gone in 2.0.1. can that be?
